myblog/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('article/', include('article.urls', namespace='article')),
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),
    path('comment/', include('comment.urls', namespace='comment')),
]

userprofile/urls.py
from django.urls import path
from . import views

app_name = 'userprofile'

urlpatterns=[
   path('login/', views.user_login, name='login'),
   path('logout/', views.user_logout, name='logout'),
   path('register/', views.user_register, name="register"),
]

userprofile/models.py
from django.db import models

# Create your models here.
class UserLoginForm:
    pass

userprofile/forms.py
from django import forms

from django.contrib.auth.models import User

class UserLoginForm(forms.Form):
   username = forms.CharField()
   password = forms.CharField()

userprofile/views.py
from django.contrib.auth import authenticate, login
from django.http import HttpResponse
from django.shortcuts import render, redirect

# Create your views here.
from userprofile.forms import UserLoginForm
from django.contrib.auth import authenticate, login, logout


def user_login(request):
    if request.method == "POST":
        user_login_form = UserLoginForm(data=request.POST)
        if user_login_form.is_valid():
            # .cleaned_data洗出合法数据
            data = user_login_form.cleaned_data
            # 检验账号、密码是否正确匹配数据库中的某个用户
            # 如果均匹配则返回这个user对象
            user = authenticate(username=data['username'], password=data['password'])
            # authenticate()方法验证用户名称和密码是否匹配，如果是，则将这个用户数据返回。
            if user:
                # 将用户数据保存在session中，实现的登陆动作
                login(request, user)
                return redirect("article:article_list")
            else:
                return HttpResponse("账号或密码输入有误,请重新输入")


        else:
            return HttpResponse("账号或密码输入不合法")


    elif request.method == "GET":
        user_login_form = UserLoginForm()
        context = {'from': user_login_form}
        return render(request, 'userprofile/login.html', context)

    else:
        return HttpResponse("请使用GET或POST请求数据")

    # 用户退出


def user_logout(request):
    logout(request)
    return redirect("article:article_list")


class UserRegisterForm:
    pass


def user_register(request):
    if request.method == 'POST':
        user_register_form = UserRegisterForm(data=request.POST)
        if user_register_form.is_valid():
            new_user = user_register_form.save(commit=False)
            # 设置密码
            new_user.set_password(user_register_form.cleaned_data['password'])
            new_user.save()
            # 保存好数据后立即登录并返回博客列表页面
            login(request, new_user)
            return redirect("article:article_list")
        else:
            return HttpResponse("注册表单输入有误。请重新输入~")
    elif request.method == 'GET':
        user_register_form = UserRegisterForm()
        context = {'form': user_register_form}
        return render(request, 'userprofile/register.html', context)
    else:
        return HttpResponse("请使用GET或POST请求数据")

templates/userprofile/login.html
{% extends "article/base.html" %}
{% load static %}
{% block title %}
   登陆
{% endblock title %}
{% block content %}
   <div class="container">
       <div class="row">
           <div class="col-12">
               <br>
               <form method="post" action=".">
                   {% csrf_token %}
                   <div class="form-group">
                       <label for="username">账号</label>
                       <input type="text" class="form-control" id="username" name="username">
                   </div>

                   <div class="form-group">
                       <label for="password">账号</label>
                       <input type="password" class="form-control" id="password" name="password">
                   </div>
                   <button type="submit" class="btn btn-primary">登陆</button>
               </form>

               <br>
               <!-- 增加这里 -->
               <h5>还没有账号？</h5>
               <h5>点击<a href='{% url "userprofile:register" %}'>注册账号</a>加入我们吧！</h5>
               <br>
                <!-- 增加这里 -->
           </div>

       </div>
   </div>
{% endblock content %}

templates/userprofile/register.html
{% extends "article/base.html" %}
{% load static %}
{% block title %}
   注册
{% endblock title %}
{% block content %}
   <div class="container">
       <div class="row">
           <div class="col-12">
               <br>
           <form method="post" action=".">
               {% csrf_token %}
               <!-- 账号 -->
               <div class="form-group col-md-4">
                   <label for="username">昵称</label>
                   <input type="text" class="form-control" id="username" name="username" required>
               </div>
               <!-- 邮箱 -->
               <div class="form-group col-md-4">
                   <label for="email">Email</label>
                   <input type="text" class="form-control" id="email" name="email">
               </div>
               <!-- 密码 -->
               <div class="form-group col-md-4">
                   <label for="password">设置密码</label>
                   <input type="password" class="form-control" id="password" name="password" required>
               </div>
               <!-- 确认密码 -->
               <div class="form-group col-md-4">
                   <label for="password2">确认密码</label>
                   <input type="password" class="form-control" id="password2" name="password2" required>
               </div>
               <!-- 提交按钮 -->
               <button type="submit" class="btn btn-primary">提交</button>
           </form>
{#                #}
           </div>
       </div>
   </div>
{% endblock content %}