article/urls.py
# 引入path
from django.urls import path


# 正在部署的应用的名称
from article import views

app_name = 'article'
urlpatterns = [
    # path函数将url映射到视图
    path('article-list/', views.article_list, name='article_list'),

    # 新增函数
    path('article-detail/<int:id>/', views.article_detail, name='article_detail'),
    path('article-create/', views.article_create, name="article_create"),
    path('article-delete/<int:id>', views.article_delete, name="article_delete"),
    path('article-update/<int:id>', views.article_update, name="article_update"),

]

comment/urls.py
from django.urls import path
from . import views

app_name = 'comments'

urlpatterns = [
    path('post-comment/<int:article_id>/', views.post_comment, name='post_comment'),
]

myblog/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('article/', include('article.urls', namespace='article')),
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),
    path('comment/', include('comment.urls', namespace='comment')),
]

userprofile/urls.py
from django.urls import path
from . import views

app_name = 'userprofile'

urlpatterns=[
   path('login/', views.user_login, name='login'),
   path('logout/', views.user_logout, name='logout'),
   path('register/', views.user_register, name="register"),
]

article/models.py
from django.db import models

# 导入内建的User模型
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils import timezone

# 博客文章数据模型
class ArticlePost(models.Model):
    # 文章作者。参数on_delete 用于指定数据删除的方式，避免两个关联表数据不一致
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    # 文章标题
    title = models.CharField(max_length=100)

    # 文章正文
    body = models.TextField()

    created = models.DateTimeField(default=timezone.now())

    # 文章更新时间 参数 auto_now=True 指定每次数据更新时自动写入当前时间
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        # ordering 指定模型返回的数据的排列顺序
        # ’-created‘ 表明数据应该以倒叙排列
        ordering = ('-created',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('article:article_detail', args=[self.id])

article/forms.py
from django import forms
from .models import ArticlePost


# 写文章表单类
class ArticlePostForm(forms.ModelForm):
    class Meta:
        # 指明数据模型来源
        model = ArticlePost
        # 定义表单包含的字段
        fields = ('title', 'body',)

article/views.py
from django.shortcuts import render
import markdown

# Create your views here.

from django.http import HttpResponse

from comment.models import Comment
from .models import ArticlePost
from django.shortcuts import render, redirect
from django.http import HttpResponse
# 引入刚才定义的ArticlePostForm
from .forms import ArticlePostForm
from django.contrib.auth.models import User


# 视图函数
def article_list(request):
    # 取出所有博客文章
    articles = ArticlePost.objects.all()
    # 需要传递给模板对象
    context = {'articles': articles}
    # render函数载入模板，并返回context对象
    return render(request, 'article/list.html', context)
    # article/list.html：模板位置          context：传入模板的对象
def article_detail(request, id, ):
    article = ArticlePost.objects.get(id=id)
    comments = Comment.objects.filter(article=id)
    article.body = markdown.markdown(article.body,
                                     extensions=[
                                         # 包含 缩写、表格等常用扩展
                                         'markdown.extensions.extra',
                                         # 语法高亮扩展
                                         'markdown.extensions.codehilite',
                                     ])

    context = {'article': article, 'comments': comments}
    # 载入模板，并返回context对象
    return render(request, 'article/detail.html', context)

def article_create(request):
   # 判断用户是否提交数据
   if request.method == "POST":
       # 将提交时数据赋值到表单实例中
       article_post_form = ArticlePostForm(data=request.POST)
       if article_post_form.is_valid():
           new_article = article_post_form.save(commit=False)
           new_article.author = User.objects.get(id=1)
           new_article.save()
           return redirect('article:article_list')
       else:
           return HttpResponse("表单内容有误,请重新填写")

   else:
       article_post_form = ArticlePostForm()
       context = {'article_post_form': article_post_form}
       return render(request, 'article/create.html', context)





def article_delete(request,id):
    article = ArticlePost.objects.get(id=id)
    article.delete()
    return redirect('article:article_list')

def article_update(request, id):
   # 获取文章对象
   article = ArticlePost.objects.get(id=id)
   if request.method =="POST":
       article_post_form = ArticlePostForm(data=request.POST)
       if article_post_form.is_valid():
           article.title = request.POST['title']
           article.body = request.POST['body']
           article.save()

           return redirect("article:article_detail", id=id)
       else:
           return HttpResponse("表单内容有误,请重新填写")


   else:
       article_post_form = ArticlePostForm()
       context = { 'article': article, 'article_post_form': article_post_form}
       return render(request, 'article/update.html', context)

templates/article/base.html
<!-- 载入静态文件 -->
{% load static %}
<!DOCTYPE html>
<!-- 网站主语言 -->
<html lang="zh-cn">
<head>
    <!-- 网站采用的字符编码 -->
    <meta charset="utf-8">
    <!-- 预留网站标题的位置 -->
    <title>{% block title %}{% endblock %}</title>
    <!-- 引入bootstrap的css文件 -->
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">

    <!-- 修改这里 -->
    <link rel="stylesheet" href="{% static 'md_css/monokai.css' %}">

</head>
<body>
    <!-- 引入导航栏 -->
    {% include 'article/header.html' %}
    <!-- 预留具体页面的位置 -->
    {% block content %}{% endblock content %}
    <!-- 引入注脚 -->
    {% include 'article/footer.html' %}
    <!-- bootstrap.js 依赖 jquery.js 和popper.js，因此在这里引入 -->
    <script src="{% static 'jquery/jquery-3.3.1.js' %}"></script>
    <script src="{% static 'popper/popper-1.14.4.js' %}"></script>
    <!-- 引入bootstrap的js文件 -->
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
</body>
</html>

templates/article/create.html
{% extends "article/base.html" %}
{% load static %}
{% block title %}
写文章
{% endblock title %}
{% block  content %}
   <div class="container">
       <div class="col-12">
           <br>
               <form method="post" action=".">
                   <!-- Django中需要POST数据的地方都必须有csrf_token -->
                   {% csrf_token %}
                   <!-- 文章标题 -->
                   <div class="form-group">
                       <!-- 标签 -->
                       <label for="title">文章标题</label>
                       <!-- 文本框 -->
                       <input type="text" class="form-control" id="title" name="title">
                   </div>
                   <!-- 文章正文 -->
                   <div class="form-group">
                       <label for="body">文章正文</label>
                       <!-- 文本区域 -->
                       <textarea type="text" class="form-control" id="body" name="body" rows="12"></textarea>
                   </div>
                   <!-- 提交按钮 -->
                   <button type="submit" class="btn btn-primary">完成</button>
               </form>
           </div>
       </div>
   </div>
{% endblock content %}

templates/article/detail.html
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "article/base.html" %}
{% load static %}
<!-- 写入 base.html 中定义的 title -->
{% block title %}
    文章详情
{% endblock title %}
<!-- 写入 base.html 中定义的 content -->
{% block content %}
<!-- 文章详情 -->
    <div class="container">
        <div class="row">
            <h1 class="col-12 mt-4">{{ article.title }}</h1>
            <div class="col-12 alert alert-success">作者： {{ article.author }}</div>
            <a href="{% url "article:article_delete" article.id %}">删除文章</a>
            <a href="{% url "article:article_update" article.id %}">编辑文章</a>
            <div class="col-12">
            <!-- 修改这个部分 -->
                <p>{{ article.body|safe }}</p>
                <!-- 修改这个部分 -->
            </div>
                            </div>

                <!-- 发表评论 -->
                <hr>
                {% if user.is_authenticated %}
                    <div>
                        <form action="{% url 'comment:post_comment' article.id %}"
                              method="post">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="body">
                                    <strong>
                                        我也要发言:
                                    </strong>
                                </label>
                                <textarea type="text" class="form-control" id="body" name="body" rows="2"></textarea>
                            </div>
                            <button type="submit" class="btn btn-primary">发送</button>
                        </form>
                    </div>
                    <br>
                    {% else %}
                        <br>
                    <h5 class="row justify-content-center">
                        请<a href="{% url 'userprofile:login' %}">登录</a>后回复
                    </h5>
                    <br>
                {% endif%}
                <!-- 显示评论 -->
                <h4>
                    共有{{ comments.count }}条评论
                </h4>
                <div>
                    {% for comment in comments %}
                        <hr>
                        <p>
                            <strong style="color: pink">
                                {{ comment.user }}
                            </strong>于
                            <span style="color: green">
                                {{ comment.created|date:"Y-m-d H:i:s" }}
                            </span>时说:
                        </p>
                        <pre style="font-family: inherit; font-size: 1em;white-space: pre-wrap;word-wrap: break-word;">        {{ comment.body }}
                        </pre>
                    {% endfor %}
                </div>
            </div>



{% endblock content %}

templates/article/footer.html
{% load static %}
<!-- Footer -->
<div>
    <br><br><br>
</div>
<footer class="py-3 bg-dark fixed-bottom">
    <div class="container">
        <p class="m-0 text-center text-white">footer</p >
    </div>
</footer>

templates/article/header.html
<!-- 定义导航栏 -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
 <div class="container">
   <!-- 导航栏商标 -->
   <a class="navbar-brand" href="#">我的博客</a>
   <!-- 导航入口 -->
   <div>
     <ul class="navbar-nav">
       <!-- 条目 -->
       <li class="nav-item">
         <a class="nav-link" href="{% url 'article:article_list' %}">文章</a>
       </li>
         <li class="nav-item">
             <a class="nav-link" href="{% url 'article:article_create' %}">写文章</a>
         </li>
         {% if user.is_authenticated %}
           <!-- 如果用户已经登录，则显示用户名下拉框 -->
           <li class="nav-item dropdown">
               <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                 {{ user.username }}
               </a>
               <a class="dropdown-menu" aria-labelledby="navbarDropdown">
                 <a class="dropdown-item" href="{%  url "userprofile:logout" %}">退出登录</a>
               </a>
           </li>
           <!-- 如果用户未登录，则显示 “登录” -->
           {% else %}
               <li class="nav-item">
                   <a class="nav-link" href="{% url 'userprofile:login' %}">登录</a>
               </li>
           <!-- if 语句在这里结束 -->
         {% endif %}
     </ul>
   </div>
 </div>
</nav>

templates/article/list.html
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "article/base.html" %}
{% load static %}

<!-- 写入 base.html 中定义的 title -->
{% block title %}
    首页
{% endblock title %}
<!-- 写入 base.html 中定义的 content -->
{% block content %}
<!-- 定义放置文章标题的div容器 -->
<div class="container">
    <div class="row mt-2">
        {% for article in articles %}
        <!-- 文章内容 -->
        <div class="col-4 mb-4">
        <!-- 卡片容器 -->
            <div class="card h-100">
                <!-- 标题 -->
                <h4 class="card-header">{{ article.title }}</h4>
                <!-- 摘要 -->
                <div class="card-body">
                    <p class="card-text">{{ article.body|slice:'100' }}...</p>
                </div>
                <!-- 注脚 -->
                <div class="card-footer">
                <!-- 修改这里 -->
                    <a href="{% url 'article:article_detail' article.id %}" class="btn btn-primary">阅读本文</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock content %}

templates/article/update.html
{% extends "article/base.html" %}
{% load static %}
{% block title %}
    修改文章
{% endblock title %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-12">
                <br>
                <form method="post" action=".">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="title">文章标题</label>
                        <input type="text" class="form-control" id="title" name="title" value="{{ article.title }}">

                    </div>
                    <div class="form-group">
                        <label for="body">文章正文</label>
                        <textarea type="text" class="form-control" id="body" name="body" rows="12">{{ article.body }}</textarea>
                    </div>
                    <button type="submit" class="btn btn-primary">完成</button>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}